<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
require 'connection.php';
require_once('TCPDF/tcpdf.php');
date_default_timezone_set('Asia/Manila');

// Get current date and time
$dateTime = date("F j, Y - g:i A");

// Get admin username
$adminEmail = 'admin@gmail.com';
$adminUsername = 'Unknown Admin';

$stmt = mysqli_prepare($conn, "SELECT username FROM admin WHERE email = ?");
mysqli_stmt_bind_param($stmt, "s", $adminEmail);
mysqli_stmt_execute($stmt);
$result = mysqli_stmt_get_result($stmt);
if ($row = mysqli_fetch_assoc($result)) {
    $adminUsername = $row['username'];
}
mysqli_stmt_close($stmt);

// TCPDF setup
$pdf = new TCPDF('L', PDF_UNIT, 'A4', true, 'UTF-8', false);
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Vincere De Floret Admin');
$pdf->SetTitle('Users Report');
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);
$pdf->SetMargins(10, 10, 10);
$pdf->SetAutoPageBreak(TRUE, 10);
$pdf->SetFont('helvetica', '', 10);
$pdf->AddPage();

// HTML content
$html = '
<h1 style="text-align:center;">Users Report</h1>
<p><b>Generated by:</b> ' . htmlspecialchars($adminUsername) . '</p>
<p><b>Date & Time:</b> ' . $dateTime . '</p>
<hr>
<table border="1" cellpadding="4">
    <thead>
        <tr>
            <th><b>ID</b></th>
            <th><b>Username</b></th>
            <th><b>Full Name</b></th>
            <th><b>Email</b></th>
            <th><b>Address</b></th>
            <th><b>Contact Number</b></th>
        </tr>
    </thead>
    <tbody>';

// Fetch users
$result = mysqli_query($conn, "SELECT id, name, CONCAT(first_name, ' ', middle_name, ' ', last_name) AS full_name, email, address, contact_number FROM users");
while ($row = mysqli_fetch_assoc($result)) {
    $html .= '
        <tr>
            <td>' . $row['id'] . '</td>
            <td>' . htmlspecialchars($row['name']) . '</td>
            <td>' . htmlspecialchars($row['full_name']) . '</td>
            <td>' . htmlspecialchars($row['email']) . '</td>
            <td>' . htmlspecialchars($row['address']) . '</td>
            <td>' . htmlspecialchars($row['contact_number']) . '</td>
        </tr>';
}

$html .= '</tbody></table>';

$pdf->writeHTML($html);
$pdf->Output('users_report.pdf', 'I');
?>
